### ISSUE TITLE
Decorator Function not working

### ISSUE THREAD

**Issue by Laistrygon** [rausc-daniel/INH17GAbschlussklausuren#3]
Fix:
def decorator(original):
  print("Bei Initialisierung")
  def wrapper(message):
    print("Bei jedem Aufruf")
    return original(message)
  return wrapper

@decorator
def display(msg):
  print(msg)

display("Heyho")
display("Na?")

**Comment by Laistrygon** [comment]
Daniel's example fixed:

def decorator_function(original_function):
  print("Executed on Declaration")
  def wrapper_function(msg):
    print("Executed on Call")
    return original_function(msg)
  return wrapper_function

@decorator_function
def display(msg):
  print(msg)
    
display("Foo")
display("Bar")

**Comment by rausc-daniel** [comment]
fixed with commit f77f9e6b56c011c5b34e52d5defaa03b83d379b0
