### ISSUE TITLE
String iterator gives different output in IDLE

### ISSUE THREAD

**Issue by Laistrygon** [rausc-daniel/INH17GAbschlussklausuren#4]
name = "Kevin"

print(name[2:4])
Doesn't give "evi" but "vi", at least in IDLE

**Comment by Laistrygon** [comment]
Python3 online editor outputs "vi" as well

**Comment by rausc-daniel** [comment]
fixed with commit b0aeb6dccfc4b0e7e1191ee80a7fe30d26aa0cbd
