### ISSUE TITLE
More on string iterator

### ISSUE THREAD

**Issue by Laistrygon** [rausc-daniel/INH17GAbschlussklausuren#5]
# gibt 3 aus weil "v" an dritter Stelle
    print(name.index("v"))

-> No, the output is 2

    # gibt "en" aus, er geht von index 2 bis 5, überspringt aber immer 2 indexe [start:end:step]
    print(name[2:5:2])

-> No, the output is "vn"

**Comment by rausc-daniel** [comment]
fixed with commit b0aeb6dccfc4b0e7e1191ee80a7fe30d26aa0cbd
